config/routes.rb
# frozen_string_literal: true
Rails.application.routes.draw do
  # get '/robots.:format' => 'sitemap#robots'
  # get '/sitemap.xml.gz' => 'sitemap#sitemap', format: :xml

  resources :articles

  # NEXT MAKE SURE USER IS VISITING OUR WWW AND NOT ANYTHING ELSE
  devise_for :users, controllers: {registrations: 'registrations', confirmations: 'confirmations'}
  devise_scope :user do
    patch '/user_update' => 'registrations#user_update'
    patch '/confirm' => 'confirmations#confirm'
  end

  get :inspiration, to: 'landing#inspiration', as: :inspiration
  get :started, to: 'landing#started', as: :get_started
  root to: 'landing#index'

end

app/views/layouts/_about_us.html.erb
<strong><%= nav_title %></strong> helps you find news that you want to.
Getting blocked by WSJ? we'll find your preferred source for the same article.

app/views/layouts/_analytics.html.erb
<% if analytics_id.to_s.length > 7 %>
  <%= javascript_include_tag("https://www.googletagmanager.com/gtag/js?id=#{analytics_id}", async: true) %>
  <script>
    window.dataLayer = window.dataLayer || [];
    function gtag() {
      dataLayer.push(arguments);
    }
    gtag('js', new Date());

    gtag('config', '<%= analytics_id %>');
  </script>
<% end %>

app/views/layouts/_footer.html.erb
<footer class="bt b--white">
  <div class="bg-black system-sans-serif">
    <% unless user_signed_in? %>
      <nav class="w-100 ph0 pv3 bb b--white-50 bg-black-80 tc">
        <%= link_to "Sign in", new_session_path(:user), class: "ttu link white-60 bg-transparent hover-white inline-flex items-center ma2 tc br2 pa2 f6" %>
        <%= link_to "Sign Up", new_registration_path(:user), class: "ttu link white-60 bg-transparent hover-white inline-flex items-center ma2 tc br2 pa2 f6" %>
      </nav>
    <% end %>
    <nav class="mw7 center w-100 cf pv4  bg-black-80">
      <div class="fl w-50">
        <h3 class="tl ma0 pa0"><%= link_to(nav_title, root_url, class: "near-white lh-title f3") %></h3>

        <p class="near-white lh-copy tl">
          <%= render partial: "layouts/about_us" %>
        </p>
      </div>
      <div class="fl w-50">
      </div>
    </nav>
    <nav class="w-100 ph0 pv3 bt b--white-50 bg-black-80 tc">
      <a class="link white-60 bg-transparent hover-white inline-flex items-center ma2 tc br2 pa2" href="https://github.com/blairanderson" title="GitHub">
        <svg class="dib h2 w2" fill="currentColor" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 16 16" fill-rule="evenodd" clip-rule="evenodd" stroke-linejoin="round" stroke-miterlimit="1.414">
          <path d="M8 0C3.58 0 0 3.582 0 8c0 3.535 2.292 6.533 5.47 7.59.4.075.547-.172.547-.385 0-.19-.007-.693-.01-1.36-2.226.483-2.695-1.073-2.695-1.073-.364-.924-.89-1.17-.89-1.17-.725-.496.056-.486.056-.486.803.056 1.225.824 1.225.824.714 1.223 1.873.87 2.33.665.072-.517.278-.87.507-1.07-1.777-.2-3.644-.888-3.644-3.953 0-.873.31-1.587.823-2.147-.083-.202-.358-1.015.077-2.117 0 0 .672-.215 2.2.82.638-.178 1.323-.266 2.003-.27.68.004 1.364.092 2.003.27 1.527-1.035 2.198-.82 2.198-.82.437 1.102.163 1.915.08 2.117.513.56.823 1.274.823 2.147 0 3.073-1.87 3.75-3.653 3.947.287.246.543.735.543 1.48 0 1.07-.01 1.933-.01 2.195 0 .215.144.463.55.385C13.71 14.53 16 11.534 16 8c0-4.418-3.582-8-8-8"/>
        </svg>
        <span class="f6 ml3 pr2">GitHub</span>
      </a>
      <a class="link white-60 bg-transparent hover-white inline-flex items-center ma2 tc br2 pa2" href="https://linkedin.com/in/andersonblair" title='linkedin'>
        <svg class="dib h2 w2" fill="currentColor" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 16 16" fill-rule="evenodd" clip-rule="evenodd" stroke-linejoin="round" stroke-miterlimit="1.414">
          <path d="M13.632 13.635h-2.37V9.922c0-.886-.018-2.025-1.234-2.025-1.235 0-1.424.964-1.424 1.96v3.778h-2.37V6H8.51V7.04h.03c.318-.6 1.092-1.233 2.247-1.233 2.4 0 2.845 1.58 2.845 3.637v4.188zM3.558 4.955c-.762 0-1.376-.617-1.376-1.377 0-.758.614-1.375 1.376-1.375.76 0 1.376.617 1.376 1.375 0 .76-.617 1.377-1.376 1.377zm1.188 8.68H2.37V6h2.376v7.635zM14.816 0H1.18C.528 0 0 .516 0 1.153v13.694C0 15.484.528 16 1.18 16h13.635c.652 0 1.185-.516 1.185-1.153V1.153C16 .516 15.467 0 14.815 0z" fill-rule="nonzero"/>
        </svg>
        <span class="f6 ml3 pr2">LinkedIn</span>
      </a>
      <a class="link white-60 bg-transparent hover-white inline-flex items-center ma2 tc br2 pa2" href="https://twitter.com/blairanderson" title="Twitter">
        <svg class="dib h2 w2" fill="currentColor" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 16 16" fill-rule="evenodd" clip-rule="evenodd" stroke-linejoin="round" stroke-miterlimit="1.414">
          <path d="M16 3.038c-.59.26-1.22.437-1.885.517.677-.407 1.198-1.05 1.443-1.816-.634.375-1.337.648-2.085.795-.598-.638-1.45-1.036-2.396-1.036-1.812 0-3.282 1.468-3.282 3.28 0 .258.03.51.085.75C5.152 5.39 2.733 4.084 1.114 2.1.83 2.583.67 3.147.67 3.75c0 1.14.58 2.143 1.46 2.732-.538-.017-1.045-.165-1.487-.41v.04c0 1.59 1.13 2.918 2.633 3.22-.276.074-.566.114-.865.114-.21 0-.416-.02-.617-.058.418 1.304 1.63 2.253 3.067 2.28-1.124.88-2.54 1.404-4.077 1.404-.265 0-.526-.015-.783-.045 1.453.93 3.178 1.474 5.032 1.474 6.038 0 9.34-5 9.34-9.338 0-.143-.004-.284-.01-.425.64-.463 1.198-1.04 1.638-1.7z" fill-rule="nonzero"/>
        </svg>
        <span class="f6 ml3 pr2">Twitter</span>
      </a>
    </nav>
  </div>
</footer>

app/views/layouts/_logo.html.erb
<p class="measure-wide center bg-near-white pa4 br3">
  <%= nav_title %> helps collect lists for people who quickly want see good gift ideas.
  When readers choose to buy our picks, we earn affiliate commissions that support our work.
</p>

app/views/layouts/_meta.html.erb
<meta charset="utf-8">
<title><%= content_for?(:title) ? "#{content_for(:title)} - #{nav_title}" : nav_title %></title>
<meta name="viewport" content="width=device-width,minimum-scale=1,initial-scale=1">
<%= tag(:link, rel: "canonical", href: request.fullpath) %>

app/views/layouts/_nav.html.erb
<% current_account_boolean = controller.respond_to?(:current_account) && current_account && current_account.persisted? %>

<nav class="db dt-l w-100 border-box bb b--black-50 bg-washed-blue pa3 ph5-l system-sans-serif ttu">
  <% if user_signed_in? %>
    <%= link_to(nav_title, accounts_path, class: 'db dtc-l v-mid mid-gray link dim w-100 w-25-l tc tl-l mb2 mb0-l') %>
  <% else %>
    <%= link_to(nav_title, root_path, class: 'db dtc-l v-mid mid-gray link dim w-100 w-25-l tc tl-l mb2 mb0-l') %>
  <% end %>

  <div class="db dtc-l v-mid w-100 w-75-l tc tr-l">
    <% if user_signed_in? %>
      <% if current_account_boolean %>
        <%= link_to("Preview", site_root_url(subdomain: current_account.slug), target: "_blank", class: 'link dim dark-gray f6 f5-l dib mr2', title: "Visit #{current_account.name}") %>
      <% end %>
      <% if controller.respond_to?(:current_accounts) && current_accounts.size > 1 %>
        <%= select_tag(:account_id, options_from_collection_for_select(current_accounts, :slug, :name, current_account.try(:slug)), prompt: "Change Account", onchange: "window.location.href='/accounts/'+this.value+'/edit'") %>
      <% end %>

      <%= link_to('Logout', destroy_user_session_path, :method => :delete, class: "link dim dark-gray f6 f5-l dib mr3 mr4-l") %>
      <%= link_to('Edit profile', edit_user_registration_path, class: "link dim dark-gray f6 f5-l dib") %>
    <% else %>
      <%= link_to('Login', new_user_session_path, class: "link dim dark-gray f6 f5-l dib mr3 mr4-l") %>
      <%= link_to('Register', new_user_registration_path, class: "link dim dark-gray f6 f5-l dib") %>
    <% end %>
  </div>
</nav>


<% if current_account_boolean %>
  <nav class="dt w-100 border-box bg-dark-blue bb b--black-50 pa0 system-sans-serif">
    <div class="dtc v-mid w-100 tc pv2">
      <%= link_to('Site Settings', edit_account_path(current_account), class: "link dim near-white f5 dib ph3") %>
      <%# link_to('Menus', account_menus_path(current_account), class: "link dim near-white f5 dib ph3") %>
      <%= link_to('All Posts', account_path(current_account), class: "link dim near-white f5 dib ph3") %>
      <%= link_to('New Post', new_account_list_path(current_account), class: "link dim near-white f5 dib ph3") %>
      <%= link_to('Need Inspiration?', inspiration_path, class: "link dim near-white f5 dib ph3") %>
    </div>
  </nav>
<% end %>

app/views/layouts/_navigation.html.erb
<nav class="db dt-l w-100 border-box pa3 ph5-l system-sans-serif ttu">
  <a class="db dtc-l v-mid mid-gray link dim w-100 w-25-l tc tl-l mb2 mb0-l" href="<%= root_path %>" title="Home"><%= nav_title %></a>

  <div class="db dtc-l v-mid w-100 w-75-l tc tr-l">
    <%= link_to('New List', new_list_path, class: "link dim dark-gray f6 f5-l dib mr3 mr4-l") %>
    <% if user_signed_in? %>
      <% if is_admin? %>
        <a class="link dim dark-gray f6 f5-l dib mr3 mr4-l" href="javascript: alert('yolo')">Hello Admin!</a>
      <% elsif is_robot? %>
        <a class="link dim dark-gray f6 f5-l dib mr3 mr4-l" href="javascript: alert('yolo')">Hello Robot!</a>
      <% end %>
      <%= link_to('Logout', destroy_user_session_path, :method => :delete, class: "link dim dark-gray f6 f5-l dib mr3 mr4-l") %>
      <%= link_to('Edit profile', edit_user_registration_path, class: "link dim dark-gray f6 f5-l dib") %>
    <% else %>
      <%= link_to('Login', new_user_session_path, class: "link dim dark-gray f6 f5-l dib mr3 mr4-l") %>
      <%= link_to('Register', new_user_registration_path, class: "link dim dark-gray f6 f5-l dib") %>
    <% end %>
  </div>
</nav>

app/views/layouts/_sidebar_items.html.erb
<form class="pt0 pb4 black-80">
  <div class="measure">
    <input id="search" placeholder="Search the Site..." class="input-reset ba b--black-20 pa3 mb2 db w-100" type="search" name="q" aria-describedby="name-desc">
  </div>
</form>


<% if current_history.length > 0 %>
  <hr/>
  <h4 class="tc">Recently Viewed</h4>
  <ul class="list ma0 pa0">
    <% current_history.each do |item| %>
      <li title="<%= item.name %>" class="tc truncate">
        <%= link_to(item.name, item.path, class: "link ttu") %>
      </li>
    <% end %>
  </ul>
  <hr/>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <%= render partial: "layouts/meta", locals: {nav_title: nav_title} %>
  <%= render partial: "layouts/analytics", locals: {analytics_id: ENV.fetch("GOOGLE_ANALYTICS")} %>
  <%= stylesheet_link_tag "application" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= render partial: 'layouts/nav' %>
  <div class="sans-serif <%= container_class_name %>">
    <% if notice %>
      <div class="bg-light-blue pa4 tc"><%= notice %></div>
    <% end %>
    <% if alert %>
      <div class="bg-light-red pa4 tc"><%= alert %></div>
    <% end %>
    <%= yield %>
    <%= render "layouts/footer" %>
  </div>

  <%= yield :javascripts %>
</body>
</html>

app/views/layouts/landing.html.erb
<!DOCTYPE html>
<html>
<head>
  <%= render partial: "layouts/meta", locals: {nav_title: nav_title} %>
  <%= render partial: "layouts/analytics", locals: {analytics_id: ENV.fetch("GOOGLE_ANALYTICS")} %>
  <%= stylesheet_link_tag "application" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>


<header class="sans-serif cf">
  <div class="set-height" style="height: 700px;">
    <div class="dt w-100  set-height center pv0" style="background-color: #2a2a72; background-image: linear-gradient(315deg, #2a2a72 0%, #009ffd 74%); height: 700px;">
      <div class="bg-near-white bb b--dark-blue absolute w-100">
        <nav id="nav" class="dt w-100 mw8 center border-box pa2 ph5-ns">
          <a class="dtc v-mid mid-gray link dim fw9 w-20" href="/"><strong><%= nav_title %></strong></a>

          <div class="dtc v-mid w-80 tr">
            <%= link_to "Sign in", new_session_path(:user), class: "link v-mid dim tc dark-gray f6 f5-ns dib mr2 mr4-ns" %>
            <%= link_to "Sign Up", new_registration_path(:user), class: "link v-mid dim tc dark-gray f6 f5-ns dib mr2 mr4-ns" %>
            <a class="f6 dib bg-animate white bg-blue hover-bg-dark-blue hover-near-white no-underline pv2 ph4 br-pill ba  v-mid b--light-blue" href="/accounts">
              Dashboard
            </a>
          </div>
        </nav>
      </div>
      <div class="tc-l dtc v-mid white mw8 center ma0 ph3" style="padding-top: 80px;">
        <style>
          .text-shadow {
            text-shadow: 0px 0px 10px #fff;
          }
        </style>

        <%= content_for(:landing_header) || "DUDE ADD SOME content_for(:landing_header)" %>
      </div>
    </div>
  </div>
</header>




<%= yield %>
<%= render "layouts/footer" %>
<%= yield :javascripts %>
</body>
</html>

app/views/layouts/site.html.erb
<!DOCTYPE html>
<html>
<head>
  <%= render partial: "layouts/meta", locals: {nav_title: current_account.nav_title} %>
  <%= render partial: "layouts/analytics", locals: {analytics_id: current_account.google_tag_manager} %>
  <%= stylesheet_link_tag "application" %>
  <%= javascript_include_tag "application" %>
</head>
<body>

<%= render partial: 'layouts/site/nav' %>
<%= render partial: 'layouts/site/header' %>

<div class="<%= site_container_class_name %>">
  <%= yield %>
</div>
<%= render partial: 'layouts/site/footer' %>
<%= yield :javascripts %>
</body>
</html>

app/views/layouts/site_preview.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= content_for?(:title) ? "#{content_for(:title)} - #{current_account.nav_title}" : current_account.nav_title %></title>
  <%= stylesheet_link_tag "application" %>
  <%= javascript_include_tag "application" %>
</head>
<body>
<p class="bg-gold mt0 pv4 tc system-sans-serif ttu">
  <strong>Heads Up!</strong> You're in preview mode! - Go back and <%= link_to("edit this post", edit_account_list_path(current_account, current_list)) %>.
</p>
<%= render partial: 'layouts/site/nav' %>
<%= render partial: 'layouts/site/header' %>
<div class="<%= site_container_class_name %>">
  <%= yield %>
</div>
<%= render partial: 'layouts/site/footer' %>
<%= yield :javascripts %>
</body>
</html>